### PR TITLE
56_content_listing

### PR DESCRIPTION
**Pull request by humphreymburu**
Updated the authors view with new fields and data export
@pcambra or @MartinMaritim Check if it's okay

### CODE REVIEW

**Comment by pcambra** [comment]
There's an extra commit from me that shouldn't be there.

**Comment by humphreymburu** [comment]
@pcambra You mean that there is an extra commit that you made that should not be there?

**Comment by pcambra** [comment]
Yes, it's not part of your PR, they should only include the relevant commits and nothing more.

**Comment by humphreymburu** [comment]
Then I should create a new pull request .

**Comment by pcambra** [comment]
Not necessarily, you can do a rebase of yours with dev and push with -f option to this same branch.

**Comment by humphreymburu** [comment]
@pcambra I  did rebase and git pushed -f ,thanks I learned something new.

**Pull request merged**
