### PR TITLE
Issue #65 - Updated entity reference validator for views as for https…

### PR DESCRIPTION
**Pull request by pcambra**
…://www.drupal.org/node/1819618

### CODE REVIEW

**Comment by pcambra** [comment]
@MartinMaritim @humphreymburu could one of you review this one? I'd like to include it in the release today

**Comment by MartinMaritim** [comment]
@pcambra will do shortly ...

**Comment by MartinMaritim** [comment]
@pcambra Is the code included in any branch under humanitarianresponse/site so that I can test it?

**Comment by MartinMaritim** [comment]
@pcambra This works well. A validation error is thrown if an non existent organization is input. It works well if an existing one is used.

**Pull request merged**
