### PR TITLE
Issue #69 - Added a tab for the global map in the assessments listing

### PR DESCRIPTION
**Pull request by pcambra**

### CODE REVIEW

**Comment by pcambra** [comment]
@MartinMaritim @humphreymburu could you take a look to this one? thanks!

**Comment by MartinMaritim** [comment]
@pcambra looking into it now ...

**Comment by MartinMaritim** [comment]
@pcambra I get a 'Access denied' message.

**Comment by pcambra** [comment]
I'll confirm with @javedyousafzai in our call later what to do about the current map node, you get access denied because you probably don't have an updated db with that particular node created.

**Comment by pcambra** [comment]
@MartinMaritim I guess your database is old, could you create this node locally and test again? https://www.humanitarianresponse.info/en/assessments/map

**Comment by MartinMaritim** [comment]
@pcambra you are right. I created the node locally and it works fine now. Thanks.

**Comment by pcambra** [comment]
Thanks for the feedback @MartinMaritim, "Home" title shouldn't be displayed now, could you verify and merge if it's the case?

**Comment by MartinMaritim** [comment]
@pcambra All good, the title is not there anymore. Thanks.

**Pull request merged**
