### PR TITLE
#58: Reduce the size of the thumbnail with no image in Document searc…

### PR DESCRIPTION
**Pull request by humphreymburu**
Hi @pcambra @MartinMaritim Check if the changes are okay.

### CODE REVIEW

**Comment by MartinMaritim** [comment]
@humphreymburu sure thing I will ...

**Comment by pcambra** [comment]
Why is this closed?

**Comment by humphreymburu** [comment]
I'm recreating it , I added css.map which should not be there.

**Comment by javedyousafzai** [comment]
@humphreymburu can I close this case?

**Comment by humphreymburu** [comment]
@javedyousafzai Close it.

**Pull request closed without merging**
